// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { configDotenv } from "dotenv";
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

configDotenv({
  path: "./src/.env",
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
