### 

@url = {{host}}/api/user

###

GET {{url}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOTk4OWQ3LTM3OWEtNzNjZS04OGU5LWNiMWFjMjRmNmU3MyIsImFjY291bnQiOiJ0ZXN0MSIsImlhdCI6MTc2MTU4MTYxMSwiZXhwIjoxNzY0MTczNjExfQ.HNrVxWbRu440L8vE2yJifNcEZj8yQszL0MEyZRxgPSQ
